### ISSUE TITLE
AllureCSharpCommons.AllureModel.label does not contain a constructor that takes 2 arguments

### ISSUE THREAD

**Issue by ghost** [allure-framework/allure-mstest-adapter#16]
I downloaded MSTestAllureAdapter project and then added AllureCSharpCommons dependency via NuGet package manager. 

After that I couldn't build MSTestAllureAdapter.Console.exe because MSTestAllureAdapter project has two errors:

> Error 2   'AllureCSharpCommons.AllureModel.label' does not contain a constructor that takes 2 arguments   D:\allure-mstest-adapter-master\MSTestAllureAdapter\AllureAdapter.cs    140 36  MSTestAllureAdapter
> 
> Error 3   'AllureCSharpCommons.AllureModel.description' does not contain a constructor that takes 2 arguments D:\allure-mstest-adapter-master\MSTestAllureAdapter\AllureAdapter.cs    151 40  MSTestAllureAdapter

I commented related lines of code and could build MSTestAllureAdapter.Console.exe but it doesn't generate any xml files in output folder. Actually I don't know whether this is a result of above-mentioned  errors or not

**Comment by someuser77** [comment]
The NuGet version of the dependent AllureCSharpCommons does not contain the API changes needed so that dependency is managed using a git submodule.
You can read in the following link how to compile it. Perhaps I should document it better. Please let me know if the issue was resolved.

https://github.com/allure-framework/allure-mstest-adapter/issues/11#issuecomment-144100257

**Comment by ghost** [comment]
Yes, it helped! Sorry for duplicate
